apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: api-gateway-pod
  template:
    metadata:
      labels:
        app: api-gateway-pod
    spec:
      containers:
      - name: api-gateway-container
        image: amolsang/puzzles-gateway-service:v3
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 7777
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATWAY_NODE_ENV
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATEWAY_APP_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GATEWAY_APP_PORT
        - name: AUTH_SERV_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_SERV_URL
        - name: PROFILE_SERV_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PROFILE_SERV_URL
        - name: RADAR_SERV_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: RADAR_SERV_URL
        - name: SESSION_SERV_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: SESSION_SERV_URL
        - name: UI_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: UI_URL
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway-service
spec:
  type: {{ .Values.apiGatewayService.type }}
  selector:
    app: api-gateway-pod
  ports:
  - protocol: TCP
    port: 7777
    targetPort: 7777
    {{ if (eq .Values.apiGatewayService.type "ClusterIP") }}
    nodePort: null
    {{ else if (eq .Values.apiGatewayService.type "LoadBalancer") }}
    nodePort: {{ .Values.apiGatewayService.nodePort }}
    {{ else if (eq .Values.apiGatewayService.type "NodePort") }}
    nodePort: {{ .Values.apiGatewayService.nodePort }}
    {{ end }}
    

