apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    app: auth-pod
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auth-pod
  template:
    metadata:
      labels:
        app: auth-pod
    spec:
      containers:
      - name: auth-container
        image: amolsang/puzzles-auth-service:v1
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 5000
        env:
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: JWT_SECRET
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: AUTH_SESSION_SECRET
        - name: CLIENT_ID
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GOOGLE_AUTH_CLIENT_ID
        - name: CLIENT_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secret
              key: GOOGLE_AUTH_CLIENT_SECRET
        - name: NODE_ENV
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_NODE_ENV
        - name: CALLBACK_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: GOOGLE_AUTH_CALLBACK_URL
        - name: APP_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_APP_HOST
        - name: APP_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: AUTH_APP_PORT
        - name: PROFILE_SERV_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: PROFILE_SERV_URL
        - name: UI_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: UI_URL
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
spec:
  type: {{ .Values.authService.type }}
  selector:
    app: auth-pod
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    {{ if (eq .Values.authService.type "ClusterIP") }}
    nodePort: null
    {{ else if (eq .Values.authService.type "LoadBalancer") }}
    nodePort: {{ .Values.authService.nodePort }}
    {{ else if (eq .Values.authService.type "NodePort") }}
    nodePort: {{ .Values.authService.nodePort }}
    {{ end }}

