apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: puzzles-ingress-ui
  annotations:
    kubernetes.io/ingress.class: "nginx"
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "-9"
spec:
  rules:
    - host: puzzles.weatherapp.com
      http:
        paths:
          - path: /auth/google/callback
            pathType: Prefix
            backend:
              service:
                name: api-gateway-service
                port:
                  number: 7777
          - path: /
            pathType: Prefix
            backend:
              service:
                name: angular-ui-service
                port:
                  number: 4200
