apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-profile-deployment
  labels:
    app: mongo-profile-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-profile-pod
  template:
    metadata:
      labels:
        app: mongo-profile-pod
    spec:
      containers:
      - name: mongodb-pod
        image: mongo:5.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 27017
      
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-profile-service
spec:
  selector:
    app: mongo-profile-pod
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017

